baseURL = '/'
languageCode = 'en-us'
title = 'tanggero'
theme = 'split'

[params.visual.image]
  enable = true
  file = "background.gif"
  position = "center center"


# Links List #1
[[params.links]]
  [params.links.list1]
    heading = "Connect"

    [[params.links.list1.link]]
      text = "soundcloud"
      url = "https://soundcloud.com/tanggero"
      new_tab = true

    [[params.links.list1.link]]
      text = "instagram"
      url = "https://www.instagram.com/freds_/"
      new_tab = true

    [[params.links.list1.link]]
      text = "email"
      url = "mailto:dj.tanggero@gmail.com"
      new_tab = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
